# This file should be used as an example when creating the config.yaml file.
# The config.yaml file should only contain variables that we do not want to
# accidentally commit.
#
# All variables listed in this file are required!

# common variables
mcd_aws_account_id_mgmt: "111111111111"
mcd_aws_account_id_shared: "111111111111"
mcd_aws_account_id_nonprod: "111111111111"
mcd_aws_account_id_prod: "111111111111"

# stack variables
# microcloud-management/.settings/monthly-budget
budget_email_address: recipient@domain.com
